import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./_component/Header";
import Navi from "./_component/navigate";
import Footer from "./_component/footer";
import { TaskProvider } from "./_component/taskProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TaskProvider>
      <div className="flex flex-col min-h-screen">
        <Header />
        <Navi />
        {children}
        <Footer />
      </div>
    </TaskProvider>
  );
}
